name: Publish Image
run-name: Publish ${{ github.repository }} image
on:
  push:
    branches:
      - main
jobs:
  publish-image:
    uses: nerney/workflows/.github/workflows/publish-image.yml@main
    permissions: 
      contents: read
      packages: write    

